import { type GetServerSideProps, type NextPage } from 'next';
import Head from 'next/head';
import { getServerAuthSession } from '../server/auth';

import Navbar from '~/components/SiteNav';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Giftable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-t from-red-200 to-purple-400">
        <article className="mx-3 mt-3 flex-grow rounded-tl-3xl rounded-tr-3xl bg-gradient-to-b from-red-100 to-slate-50 py-5 px-5 shadow-2xl shadow-black md:mx-20 md:mt-20 md:px-20">
          <Navbar />
          <section className="w-1/2">
            <div className="w-fit rounded-lg bg-orange-200 p-2">
              <h2 className="font-semibold text-orange-500">
                🎂 the ultimate birthday reminder
              </h2>
            </div>
            <h1 className=" text-8xl font-medium">
              Give the <span className="text-cyan-700">perfect</span> gift,
              every time ✨
            </h1>
            <ul className="mt-4 space-y-4 text-2xl font-light">
              <li>Organize gift ideas for your friends and family. </li>
              <li>Save a wishlist for yourself. </li>
              <li>Never forget a special occasion again</li>
            </ul>
          </section>
        </article>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getServerAuthSession(ctx);

  if (session) {
    return {
      redirect: {
        destination: '/app/dashboard',
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};

export default Home;
