import { Cookie } from '@next/font/google';
import Head from 'next/head';
import Navbar from '~/components/layouts/website/SiteNav';

const cookie = Cookie({
  variable: '--font-cookie',
  subsets: ['latin'],
  weight: '400',
});

interface IPrimaryLayout {
  children: React.ReactNode;
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Giftable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col bg-gradient-to-t from-red-200 to-purple-400 ${cookie.variable}`}
      >
        <div className="mx-3 mt-3 flex-grow rounded-tl-3xl rounded-tr-3xl bg-gradient-to-b from-red-100 to-slate-50 py-5 px-5 shadow-2xl shadow-black md:mx-20 md:mt-20 md:px-20">
          <Navbar />
          <div className="w-full">{children}</div>
        </div>
      </main>
    </>
  );
};

export default PrimaryLayout;
