name: CI

on: [push, pull_request]

env:
  DATABASE_URL: 'https://fake.com'
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'fakeKey'
  CLERK_SECRET_KEY: 'fakeSecret'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint
